num1 = int(input("Enter the first number"))
num2 = int(input("Enter the second number"))
num3 = int(input("Enter the third number"))
minm_val = min(num1,num2,num3)
maxm_val = max(num1,num2,num3)
print("The minimum value is %d"%(minm_val))
print("The maximum value is %d"%(maxm_val))